# Generated by Django 3.1.7 on 2021-03-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla01',
            fields=[
                ('colid', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('colnombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('C_Login', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('N_Pass', models.CharField(max_length=8)),
                ('N_Nombre', models.CharField(max_length=70)),
                ('F_Activo', models.BooleanField(default=False)),
                ('D_FinVig', models.DateField()),
                ('M_Ingresos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistComercial.question')),
            ],
        ),
    ]
